apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: samurenko
data:
  SWAGGER_URL: ./swagger.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: samurenko
type: Opaque
data:
  DATABASE_URI: cG9zdGdyZXNxbCtwc3ljb3BnMjovL215dXNlcjpwYXNzd2RAcG9zdGdyZXMvbXlhcHA=