apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: microservicearchitecture
build:
  artifacts:
    - image: samurenkoroma/homework
      context: api
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: samurenkoroma/client
      context: client
      sync:
        infer:
          - '**/*.py'
    - image: samurenkoroma/swagger
      context: doc
      sync:
        infer:
          - 'swagger.yaml'
deploy:
  kubectl:
    manifests:
      - app-config.yaml
      - ingress.yaml
      - service.yaml
      - client.yaml
      - swagger.yaml
