replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "13"

service:
  name: postgres
  type: NodePort
  port: 5432

ingress:
  enabled: false

autoscaling:
  enabled: false

externalPostgresql:
  username: myuser
  password: passwd
  db: myapp
  host: "postgres"
  port: "5432"

namespace: "samurenko"
appLabel: "postgres"