apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: {{.Values.namespace}}
spec:
  serviceName: "{{.Values.service.name}}"
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.appLabel}}
  template:
    metadata:
      labels:
        app: {{.Values.appLabel}}
    spec:
      containers:
        - name: {{ .Values.image.repository }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5432
              name: postgredb
          env:
            - name: POSTGRES_DB
              value: {{.Values.externalPostgresql.db}}
            - name: POSTGRES_USER
              value: {{.Values.externalPostgresql.username}}
            - name: POSTGRES_PASSWORD
              value: {{.Values.externalPostgresql.password}}
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: standard
        resources:
          requests:
            storage: 4Gi