apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.appLabel}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
  selector:
    app: {{.Values.appLabel}}
